### ISSUE TITLE
Planning for our "1.0" SDK release

### ISSUE THREAD

**Issue by MeltyBot** [meltano/sdk#188]
Migrated from GitLab: https://gitlab.com/meltano/sdk/-/issues/189

Originally created by @aaronsteers on 2021-08-13 18:36:49

---

This issue will be used to track and discuss those items we believe are required for a stable and robust `v1.0` launch of the Tap and Target SDKs.

Tap SDK:

- [x] Fully implement selection metadata
- [x] Implement state tracking for incremental sync
- [x] Implement catalog discovery
- [ ] Implement a DatabaseStream class for DB-type sources ([#74](https://gitlab.com/meltano/sdk/-/issues/74))
- [ ] Support LOG_BASED replication for DB-type sources ([#74](https://gitlab.com/meltano/sdk/-/issues/74))
- [ ] Support the ACTIVATE_MESSAGE unofficial singer extension ([#18](https://gitlab.com/meltano/sdk/-/issues/18))

Target SDK:

- [ ] Support deleting (soft or hard deletes) when receiving the ACTIVATE_MESSAGE message type (unofficial singer extension) ([#18](https://gitlab.com/meltano/sdk/-/issues/18))

Both SDKs:

- [ ] Have sufficient tests, including unit tests and integration tests
- [ ] Include out-of-box CI templates (e.g. for instance, with Github Actions)

## Call for Comments

Want to suggest other must-have features for our `1.0` release checklist? Please add your feedback in the comments below.

**Comment by MeltyBot** [comment]
[View 12 previous comments from the original issue on GitLab](https://gitlab.com/meltano/sdk/-/issues/189)
